export * as encodingTOML from "https://deno.land/std@0.77.0/encoding/toml.ts";
export * as encodingYAML from "https://deno.land/std@0.77.0/encoding/yaml.ts";
export * as fs from "https://deno.land/std@0.77.0/fs/mod.ts";
export * as path from "https://deno.land/std@0.77.0/path/mod.ts";
export * as colors from "https://deno.land/std@0.77.0/fmt/colors.ts";
export * as docopt from "https://denopkg.com/Eyal-Shalev/docopt.js@v1.0.5/src/docopt.ts";
export * as govnSvcImport from "https://denopkg.com/gov-suite/governed-service-helpers@v0.3.2/import.ts";
export * as govnSvcVersion from "https://denopkg.com/gov-suite/governed-service-helpers@v0.3.2/version.ts";
export * as safety from "https://denopkg.com/shah/ts-safety@v0.3.0/mod.ts";
