export * as encodingTOML from "https://deno.land/std@0.83.0/encoding/toml.ts";
export * as encodingYAML from "https://deno.land/std@0.83.0/encoding/yaml.ts";
export * as colors from "https://deno.land/std@0.83.0/fmt/colors.ts";
export * as fs from "https://deno.land/std@0.83.0/fs/mod.ts";
export * as path from "https://deno.land/std@0.83.0/path/mod.ts";
export * as docopt from "https://denopkg.com/Eyal-Shalev/docopt.js@v1.0.5/src/docopt.ts";
export * as govnSvcImport from "https://denopkg.com/gov-suite/governed-service-helpers@v0.3.10/import.ts";
export * as govnSvcVersion from "https://denopkg.com/gov-suite/governed-service-helpers@v0.3.10/version.ts";
// export * as extend from "../ts-extend/mod.ts";
// export * as inspectAsset from "../ts-inspect/asset/mod.ts";
// export * as inspect from "../ts-inspect/mod.ts";
export * as extend from "https://denopkg.com/shah/ts-extend@v0.1.0/mod.ts";
export * as inspectAsset from "https://denopkg.com/shah/ts-inspect@v0.9.0/asset/mod.ts";
export * as inspect from "https://denopkg.com/shah/ts-inspect@v0.9.0/mod.ts";
export * as safety from "https://denopkg.com/shah/ts-safety@v0.3.1/mod.ts";
export * as shell from "https://denopkg.com/shah/tsd-shell@v0.9.2/mod.ts";
